import { Link } from "react-router-dom";
import Footer from "../../components/general/Footer";
import Splash from "../../components/general/Splash";

export default function Privacy() {

    const LAST_UPDATE = new Date("2025-09-23");

    const STYLE = {
        BLOCK: "rounded-lg ring-2 ring-white/25 p-4",
        SECTION_TITLE: "text-xl text-white font-medium",
        SUBSECTION_TITLE: "text-lg text-white/50 font-medium",
        PARAGRAPH: "text-base/snug ",
        PARAGRAPH_M: "text-base/snug mt-4",
        HIGHLIGHT: "font-medium decoration-2 underline decoration-accent underline-offset-2",
        STRONG: "font-semibold text-white"
    }

    return (
        <>
            <Splash uppertext="Privacy Policy" />

            <div className="container mx-auto max-w-6xl p-4 xl:px-0 space-y-4">
                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Privacy Policy
                    </h1>
                    <span className="text-sm text-white/50">
                        Last updated: {LAST_UPDATE.toLocaleDateString("en-US", { year: 'numeric', month: 'long', day: 'numeric' })}
                    </span>
                    <p className={STYLE.PARAGRAPH_M}>
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    </p>
                    <p className={STYLE.PARAGRAPH}>
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE + " mb-2"}>
                        Interpretation and Definitions
                    </h1>
                    <p className={STYLE.PARAGRAPH}>
                        <ul className="list-none list-inside space-y-2">
                            <li><span className={STYLE.STRONG}>Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><span className={STYLE.STRONG}>Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Flown Records.</li>
                            <li><span className={STYLE.STRONG}>Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><span className={STYLE.STRONG}>Country</span> refers to: Portugal</li>
                            <li><span className={STYLE.STRONG}>Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li><span className={STYLE.STRONG}>Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
                            <li><span className={STYLE.STRONG}>Service</span> refers to the Website.</li>
                            <li><span className={STYLE.STRONG}>Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                            <li><span className={STYLE.STRONG}>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>  
                            <li><span className={STYLE.STRONG}>Website</span> refers to Flown Records, accessible from flownrecords.live</li>
                            <li><span className={STYLE.STRONG}>You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE + " mb-2"}>
                        Collecting and Using Your Personal Data
                    </h1>
                    <h2 className={STYLE.SUBSECTION_TITLE}>
                        Personal Data
                    </h2>

                    <p className={STYLE.PARAGRAPH}>
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                        <ul className="list-disc list-inside space-y-2 mt-2">
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Profile pictures</li>
                            <li>Country, Region or City</li>
                            <li>Usage Data</li>
                            <li>Flight data</li>
                            
                        </ul>
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Tracking Technologies and Cookies
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                        <ul className="list-disc list-inside space-y-2 mt-2">
                            <li><span className={STYLE.STRONG}>Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                            <li><span className={STYLE.STRONG}>Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                        </ul>
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Use of Your Personal Data
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        The Company may use Personal Data for the following purposes:
                        <ul className="list-disc list-inside space-y-2 mt-2">
                            <li>Create and manage your account.</li>
                            <li>Display your flight data to you.</li>
                            <li>Generate reports you request.</li>
                            <li>Communicate with you if needed (support, updates, etc.).</li>
                        </ul>
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Retention of Your Personal Data
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Transfer of Your Personal Data
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Delete Your Personal Data
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        Our Service may give You the ability to delete certain information about You from within the Service.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Disclosure of Your Personal Data
                    </h1>
                    <h2 className={STYLE.SUBSECTION_TITLE}>
                        Business Transactions
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Law enforcement
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                    </p>
                    <h2 className={STYLE.SUBSECTION_TITLE + " mt-4"}>
                        Other legal requirements
                    </h2>
                    <p className={STYLE.PARAGRAPH}>
                        The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                        <ul className="list-disc list-inside space-y-2 mt-2">
                            <li>Comply with a legal obligation</li>
                            <li>Protect and defend the rights or property of the Company</li>
                            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                            <li>Protect the personal safety of Users of the Service or the public</li>
                            <li>Protect against legal liability</li>
                        </ul>
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Children's Privacy
                    </h1>
                    <p className={STYLE.PARAGRAPH}>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Links to Other Websites
                    </h1>
                    <p className={STYLE.PARAGRAPH}>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Changes to this Privacy Policy
                    </h1>
                    <p className={STYLE.PARAGRAPH}>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                    </p>
                    <p className={STYLE.PARAGRAPH_M}>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </p>
                </div>

                <div className={STYLE.BLOCK}>
                    <h1 className={STYLE.SECTION_TITLE}>
                        Contact us
                    </h1>
                    <p className={STYLE.PARAGRAPH}>
                        If you have any questions about this Privacy Policy, You can contact us at <Link to="https://flownrecords.live/contact" className={STYLE.HIGHLIGHT}>flownrecords.live/contact</Link>.
                    </p>
                </div>
            </div>

            <Footer />
        </>
    )
}